title: Open-Source Business Multi Cloud Solutions
description: Open-Source-Software around Infrastructure Automation Terraform and Odoo Community Business APPs.
logo: /assets/img/TerradooCloud-web.png
google_analytics: G-HYDXRB0XDT

theme: jekyll-theme-minimal
